name: 'Actions Status Discord'
description: 'Post Github Actions CI status to Discord'
author: 'Sarisia'

inputs:
  webhook:
    description: "Discord webhook endpoint. If not set, env.DISCORD_WEBHOOK will be used."
    required: false
  status:
    description: "Job status. Should be bound to job.status. Default to success."
    required: false
    default: 'success'
  job:
    description: "Deprecated. Job name included in message title. Same as title input."
    required: false
  title:
    description: "String included in embed title. Overrides job input."
    required: false
  description:
    description: "Description included in message"
    required: false
  nofail:
    description: "This action won't make workflow failed by default."
    required: false
    default: 'true'
  nodetail:
    description: "Suppress detailed embed fields"
    required: false
    default: 'false'
  color:
    description: "Overrides Discord embed color"
    required: false
  username:
    description: "Overrides Discord webhook username"
    required: false
  avatar_url:
    description: "Overrides Discord webhook avatar url"
    required: false

runs:
  using: 'node12'
  main: 'lib/main.js'

branding:
  color: 'blue'
  icon: 'send'
